<script setup lang="ts">
import DocsA11yNote from '@docs/components/DocsA11yNote.vue'
import DocsCode from '@docs/components/DocsCode.vue'
import DocsPreview from '@docs/components/DocsPreview.vue'
import DocsPropsTable from '@docs/components/DocsPropsTable.vue'
import DocsSection from '@docs/components/DocsSection.vue'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n({
  messages: {
    fr: {
      title: 'Sélecteur de date',
      desc: 'Champ de saisie de date avec calendrier intégré, adapté au format administratif <code>jj/mm/aaaa</code>. Émet l’événement <code>bj:datepicker</code>.',
      'section-example': 'Exemple',
      'section-minmax': 'Avec bornes min/max',
      'section-css': 'Classes CSS',
      'section-a11y': 'Accessibilité',
      'prop-datepicker': 'Conteneur principal.',
      'prop-datepicker-input': 'Champ de saisie de la date.',
      'prop-datepicker-trigger': 'Bouton d’ouverture du calendrier.',
      'prop-datepicker-calendar':
        'Panneau calendrier (généré par JS).',
      'prop-datepicker-day-today': 'Jour actuel.',
      'prop-datepicker-day-selected': 'Jour sélectionné.',
      'prop-datepicker-sm': 'Variante compacte.',
      'a11y-note':
        'Le calendrier a <code>role="dialog"</code>. Navigation clavier complète : flèches, Entrée pour sélectionner, Échap pour fermer. Le champ accepte la saisie manuelle au format <code>jj/mm/aaaa</code>.',
    },
    en: {
      title: 'Date picker',
      desc: 'Date field with built-in calendar, suited to the administrative <code>dd/mm/yyyy</code> format. Emits the <code>bj:datepicker</code> event.',
      'section-example': 'Example',
      'section-minmax': 'With min/max bounds',
      'section-css': 'CSS classes',
      'section-a11y': 'Accessibility',
      'prop-datepicker': 'Main container.',
      'prop-datepicker-input': 'Date input field.',
      'prop-datepicker-trigger': 'Button to open the calendar.',
      'prop-datepicker-calendar':
        'Calendar panel (generated by JS).',
      'prop-datepicker-day-today': 'Current day.',
      'prop-datepicker-day-selected': 'Selected day.',
      'prop-datepicker-sm': 'Compact variant.',
      'a11y-note':
        'The calendar uses <code>role="dialog"</code>. Full keyboard support: arrows, Enter to select, Escape to close. The field accepts manual entry in <code>dd/mm/yyyy</code> format.',
    },
  },
})

const codeExample = `<div class="bj-datepicker" data-bj-datepicker>
  <div class="bj-datepicker__field">
    <input type="text" class="bj-datepicker__input" placeholder="jj/mm/aaaa" />
    <button type="button" class="bj-datepicker__trigger" aria-label="Ouvrir le calendrier">
      <i class="ri-calendar-line" aria-hidden="true"></i>
    </button>
  </div>
</div>`

const codeMinMax = `<div class="bj-datepicker" data-bj-datepicker
     data-bj-datepicker-min="01/01/2024"
     data-bj-datepicker-max="31/12/2026">
  …
</div>`

const propsRows = computed(() => [
  { name: 'bj-datepicker', description: t('prop-datepicker') },
  {
    name: 'bj-datepicker__input',
    description: t('prop-datepicker-input'),
  },
  {
    name: 'bj-datepicker__trigger',
    description: t('prop-datepicker-trigger'),
  },
  {
    name: 'bj-datepicker__calendar',
    description: t('prop-datepicker-calendar'),
  },
  {
    name: 'bj-datepicker__day--today',
    description: t('prop-datepicker-day-today'),
  },
  {
    name: 'bj-datepicker__day--selected',
    description: t('prop-datepicker-day-selected'),
  },
  { name: 'bj-datepicker--sm', description: t('prop-datepicker-sm') },
])
</script>

<template>
  <h1 class="bj-h1" style="margin-top: var(--bj-spacing-4v)">
    {{ t('title') }}
  </h1>
  <p
    class="bj-text-lg"
    style="max-width: 44rem; color: var(--bj-text-alt)"
    v-html="t('desc')"
  />

  <DocsSection id="sec-exemple" :title="t('section-example')">
    <DocsPreview>
      <div class="bj-datepicker" data-bj-datepicker>
        <div class="bj-datepicker__field">
          <input
            type="text"
            class="bj-datepicker__input"
            placeholder="jj/mm/aaaa"
          />
          <button
            type="button"
            class="bj-datepicker__trigger"
            aria-label="Ouvrir le calendrier"
          >
            <i class="ri-calendar-line" aria-hidden="true"></i>
          </button>
        </div>
      </div>
    </DocsPreview>
    <DocsCode :code="codeExample" />
  </DocsSection>

  <DocsSection id="sec-bornes" :title="t('section-minmax')">
    <DocsPreview>
      <div
        class="bj-datepicker"
        data-bj-datepicker
        data-bj-datepicker-min="01/01/2024"
        data-bj-datepicker-max="31/12/2026"
      >
        <div class="bj-datepicker__field">
          <input
            type="text"
            class="bj-datepicker__input"
            placeholder="jj/mm/aaaa"
          />
          <button
            type="button"
            class="bj-datepicker__trigger"
            aria-label="Ouvrir le calendrier"
          >
            <i class="ri-calendar-line" aria-hidden="true"></i>
          </button>
        </div>
      </div>
    </DocsPreview>
    <DocsCode :code="codeMinMax" />
  </DocsSection>

  <DocsSection id="sec-classes-css" :title="t('section-css')">
    <DocsPropsTable :rows="propsRows" />
  </DocsSection>

  <DocsSection id="sec-accessibilite" :title="t('section-a11y')">
    <DocsA11yNote>
      <span v-html="t('a11y-note')"></span>
    </DocsA11yNote>
  </DocsSection>
</template>
