// Extracted from docs-legacy/premiers-pas/ia.html (<div class="docs-code"> blocks)

export const iaCodeLlmsUrl = "https://dsbj.site/llms.txt"

export const iaCodeLlmsFullUrl = "https://dsbj.site/llms-full.txt"

export const iaMdcGeneral = "---\ndescription: Conventions générales du Design Système du Bénin (DSBJ)\nglobs: [\"**/*.html\", \"**/*.scss\", \"**/*.ts\", \"**/*.css\"]\n---\n\n# DSBJ - Conventions générales\n\n## Préfixe CSS\n- Toutes les classes CSS utilisent le préfixe `bj-` (ex: `bj-btn`, `bj-card`)\n- Toutes les variables CSS utilisent `--bj-*` (ex: `--bj-spacing-4v`, `--bj-color-vert-benin-main-491`)\n- Les composants suivent la convention BEM : `bj-composant`, `bj-composant__element`, `bj-composant--modifier`\n\n## Structure des composants\n- Styles SCSS : `src/component/<name>/style/_<name>.scss`\n- JavaScript : `src/js/<name>.ts` (utilise `register()` de `src/js/core.ts`)\n- Documentation : `docs/composants/<name>.html`\n\n## Attributs data\n- Les hooks JavaScript utilisent `data-bj-*` (ex: `data-bj-accordion-btn`, `data-bj-modal-open`)\n- L'état ouvert/actif est marqué par `data-bj-expanded`\n\n## Polices et icônes\n- Corps : Montserrat (400, 500, 600, 700)\n- Titres éditoriaux : Spectral (400, 600)\n- Icônes : Remix Icon 4.1 (`ri-*`), toujours avec `aria-hidden=\"true\"` quand décoratives\n\n## Package\n- Installer avec `bun add @flrxnt/dsbj`\n- Import : `import '@flrxnt/dsbj'` (auto-init JS + CSS)\n- CSS seul : `import '@flrxnt/dsbj/css'`\n- SCSS : `@use '@flrxnt/dsbj/scss'`"

export const iaMdcAccessibility = "---\ndescription: Règles d'accessibilité WCAG 2.1 AA pour le DSBJ\nglobs: [\"**/*.html\", \"**/*.ts\"]\n---\n\n# DSBJ - Accessibilité (WCAG 2.1 AA)\n\n## Règles obligatoires\n- Un seul `<h1>` par page, hiérarchie de titres stricte (h1 > h2 > h3, pas de saut)\n- Skip links en début de page : `<div class=\"bj-skiplinks\"><a class=\"bj-skiplink\" href=\"#main\">Accéder au contenu</a></div>`\n- Attribut `lang=\"fr\"` sur `<html>`, cohérent avec le contenu visible\n- Alt text sur toutes les images (`alt=\"\"` si purement décorative)\n- Contraste minimum AA (4.5:1 texte normal, 3:1 grand texte)\n\n## Composants interactifs\n- `aria-expanded` + `aria-controls` sur les boutons qui ouvrent/ferment (accordéon, menu, dropdown)\n- `aria-hidden=\"true\"` sur les icônes décoratives (`<i class=\"ri-*\">`)\n- `aria-label` sur les boutons sans texte visible (boutons icône)\n- `role=\"dialog\"` + `aria-modal=\"true\"` + `aria-labelledby` sur les modales\n- `role=\"tablist\"`, `role=\"tab\"`, `role=\"tabpanel\"` + `aria-selected` sur les onglets\n- `role=\"alert\"` sur les alertes dynamiques injectées\n- `aria-current=\"page\"` sur le lien actif dans la navigation et le breadcrumb\n\n## Formulaires\n- Chaque champ a un `<label>` avec `for` pointant vers l'`id` du champ\n- Erreurs liées via `aria-describedby` + `aria-invalid=\"true\"`\n- Focus visible avec `:focus-visible` (jamais supprimer l'outline)\n\n## Navigation clavier\n- `focusTrap` de core.ts pour les overlays (modale, galerie)\n- Tous les éléments interactifs accessibles au Tab\n- Échap ferme les modales et dropdowns"

export const iaMdcSeo = "---\ndescription: Règles SEO pour les pages utilisant le DSBJ\nglobs: [\"**/*.html\"]\n---\n\n# DSBJ - SEO\n\n## Head obligatoire\n- `<title>` structuré : \"Page - Section - DSBJ\" ou \"Page - Mon service - République du Bénin\"\n- `<meta name=\"description\">` unique par page (150-160 caractères)\n- `<link rel=\"canonical\">` avec URL absolue\n- `<meta name=\"theme-color\" content=\"#008751\">`\n\n## Open Graph\n- `og:title`, `og:description`, `og:type` (website), `og:url`, `og:locale` (fr_BJ)\n- `og:image` avec image de partage (1200x630px recommandé)\n\n## Twitter Card\n- `twitter:card` (summary_large_image), `twitter:title`, `twitter:description`\n\n## Structure sémantique\n- `<header role=\"banner\">`, `<main id=\"main\" role=\"main\">`, `<footer role=\"contentinfo\">`\n- `<nav>` avec `aria-label` pour chaque bloc de navigation\n- Breadcrumb dans un `<nav aria-label=\"Fil d'Ariane\">` avec `<ol>`\n\n## Données structurées\n- JSON-LD WebSite + Organization sur la page d'accueil\n- JSON-LD BreadcrumbList sur les pages intérieures"

export const iaCodeMcpInstall = "cd mcp && bun install"

export const iaCodeMcpJson = "{\n  \"mcpServers\": {\n    \"dsbj\": {\n      \"command\": \"bun\",\n      \"args\": [\"run\", \"mcp/src/index.ts\"]\n    }\n  }\n}"

export const iaPromptPageGouv = "En utilisant le Design Système du Bénin (DSBJ), génère une page d'accueil pour un portail de service public. La page doit inclure :\n- Le header institutionnel (bj-header) avec logo République du Bénin et navigation\n- Un hero avec titre et bouton d'action\n- Une grille de 4 tuiles (bj-tile) pour les services principaux\n- Un pied de page (bj-footer) avec mentions légales\n- Skip links d'accessibilité\nUtilise les classes bj-* et les variables CSS --bj-*. Respecte WCAG 2.1 AA."

export const iaPromptForm = "Crée un formulaire de contact accessible avec le DSBJ :\n- bj-input-group pour nom, email, sujet\n- bj-select-group pour le département\n- Textarea pour le message\n- bj-checkbox pour l'acceptation des CGU\n- bj-btn pour la soumission\n- Messages d'erreur avec bj-message--error et aria-describedby\n- Validation côté client avec aria-invalid=\"true\" sur les champs en erreur"

export const iaPromptDashboard = "Génère un dashboard administratif avec le DSBJ :\n- Breadcrumb (bj-breadcrumb) en haut\n- Onglets (data-bj-tabs) avec 3 panneaux : Vue d'ensemble, Statistiques, Paramètres\n- Dans chaque panneau : des cartes (bj-card) et un tableau (bj-table) avec données\n- Une modale (bj-modal) de confirmation pour les actions destructives\n- Alerte de succès (bj-alert--success) après validation\nAssure-toi que les rôles ARIA sont corrects sur les onglets et la modale."

export const iaPromptContexteLlm = "Tu es un développeur front-end spécialisé dans le Design Système du Bénin (DSBJ).\nVoici la documentation complète : https://dsbj.site/llms-full.txt\n\nRègles :\n- Utilise uniquement les classes bj-* et variables --bj-*\n- Respecte WCAG 2.1 AA (ARIA, focus, contraste, hiérarchie des titres)\n- Un seul h1 par page, skip links obligatoires\n- Icônes décoratives : aria-hidden=\"true\"\n- Composants interactifs : aria-expanded, aria-controls, aria-label\n- Polices : Montserrat (corps) + Spectral (titres éditoriaux)\n- Icônes : Remix Icon (ri-*)"

